module ReprovideException

include "./provideException"
from ProvideException use { exception MyException, excVal1 }

let excVal2 = ProvideException.MyException

provide { exception MyException, excVal1, excVal2 }
